# Project: 1_domaci_client
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = client.o
LINKOBJ  = client.o
LIBS     = -L"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/lib" -L"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -lws2_32 -lm
INCS     = -I"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/include" -I"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/include" -I"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = 1_domaci_client.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = E:\luka bitne_stvari\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

client.o: client.c
	$(CC) -c client.c -o client.o $(CFLAGS)
