# Project: 1_domaci_server
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../../../multithreading/Multithread_code/AcceptTCPConnectionWS.o ../../../multithreading/Multithread_code/CreateTCPServerSocketWS.o ../../../multithreading/Multithread_code/DieWithErrorWS.o ../../../multithreading/Multithread_code/HandleTCPClient.o server.o HandleTCPClient_version_for_homework.o
LINKOBJ  = ../../../multithreading/Multithread_code/AcceptTCPConnectionWS.o ../../../multithreading/Multithread_code/CreateTCPServerSocketWS.o ../../../multithreading/Multithread_code/DieWithErrorWS.o ../../../multithreading/Multithread_code/HandleTCPClient.o server.o HandleTCPClient_version_for_homework.o
LIBS     = -L"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/lib" -L"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -lws2_32
INCS     = -I"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/include" -I"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/include" -I"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/luka bitne_stvari/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = 1_domaci_server.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = E:\luka bitne_stvari\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../../../multithreading/Multithread_code/AcceptTCPConnectionWS.o: ../../../multithreading/Multithread_code/AcceptTCPConnectionWS.c
	$(CC) -c ../../../multithreading/Multithread_code/AcceptTCPConnectionWS.c -o ../../../multithreading/Multithread_code/AcceptTCPConnectionWS.o $(CFLAGS)

../../../multithreading/Multithread_code/CreateTCPServerSocketWS.o: ../../../multithreading/Multithread_code/CreateTCPServerSocketWS.c
	$(CC) -c ../../../multithreading/Multithread_code/CreateTCPServerSocketWS.c -o ../../../multithreading/Multithread_code/CreateTCPServerSocketWS.o $(CFLAGS)

../../../multithreading/Multithread_code/DieWithErrorWS.o: ../../../multithreading/Multithread_code/DieWithErrorWS.c
	$(CC) -c ../../../multithreading/Multithread_code/DieWithErrorWS.c -o ../../../multithreading/Multithread_code/DieWithErrorWS.o $(CFLAGS)

../../../multithreading/Multithread_code/HandleTCPClient.o: ../../../multithreading/Multithread_code/HandleTCPClient.c
	$(CC) -c ../../../multithreading/Multithread_code/HandleTCPClient.c -o ../../../multithreading/Multithread_code/HandleTCPClient.o $(CFLAGS)

server.o: server.c
	$(CC) -c server.c -o server.o $(CFLAGS)

HandleTCPClient_version_for_homework.o: HandleTCPClient_version_for_homework.c
	$(CC) -c HandleTCPClient_version_for_homework.c -o HandleTCPClient_version_for_homework.o $(CFLAGS)
